In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data_export2.csv')
df.head()

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Consent,Q15
0,2022-12-06 14:06:19,2022-12-06 14:30:59,IP Address,24.56.247.88,100,1479,True,2022-12-06 14:30:59,R_3ERxMwtFvwzHpFA,NaN,NaN,NaN,NaN,47.5834,-122.2979,anonymous,EN,Yes,NaN
1,2022-12-08 14:49:19,2022-12-08 14:49:28,IP Address,128.61.73.2,25,8,False,2022-12-15 14:49:35,R_RFu62n8LR7nWbsd,NaN,NaN,NaN,NaN,NaN,NaN,anonymous,EN,Yes,NaN
2,2022-12-02 21:55:51,2022-12-08 15:05:45,IP Address,216.110.195.70,75,493794,False,2022-12-15 15:05:49,R_0AE0BhMtNqAnfy1,NaN,NaN,NaN,NaN,NaN,NaN,anonymous,EN,Yes,NaN
3,2022-12-23 13:11:30,2022-12-23 13:44:40,IP Address,64.251.50.109,100,1990,True,2022-12-23 13:44:41,R_25L3vArkuEW8jYo,NaN,NaN,NaN,NaN,41.8501,-72.4649,anonymous,EN,Yes,NaN
4,2023-01-25 13:11:56,2023-01-26 14:19:49,IP Address,128.61.19.112,100,90472,True,2023-01-26 14:19:50,R_2tL1M0wqV1cyakS,NaN,NaN,NaN,NaN,33.7838,-84.4455,anonymous,EN,Yes,NaN

In [3]:
ips = df[['StartDate','IPAddress']]
ips.columns = ['timestamp', 'ip_address']
ips.head()

             timestamp      ip_address
0  2022-12-06 14:06:19    24.56.247.88
1  2022-12-08 14:49:19     128.61.73.2
2  2022-12-02 21:55:51  216.110.195.70
3  2022-12-23 13:11:30   64.251.50.109
4  2023-01-25 13:11:56   128.61.19.112

In [4]:
ips.to_csv('qualtrics_ip.csv', index=False)